name: Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup component add clippy

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Clippy
        run: cargo clippy

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup component add rustfmt

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Rustfmt
        run: cargo fmt --check